import { StyleSheet } from 'react-native';

import { Fonts } from '@/constants/theme';

export const palette = {
  background: '#f4efe4',
  ink: '#1e2430',
  mutedInk: '#596375',
  card: '#fffaf1',
  border: '#d4c5ae',
  accent: '#b5523f',
  accentDeep: '#7e2f22',
  accentSoft: '#efd6c8',
  slate: '#2c4657',
  slateSoft: '#d2e0e7',
  good: '#2f7d62',
  evil: '#8d2f3f',
  gold: '#9f7a2d',
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
  },
  scrollContent: {
    paddingBottom: 48,
  },
  content: {
    gap: 18,
    paddingHorizontal: 18,
    paddingTop: 12,
  },
  backgroundShapeTop: {
    position: 'absolute',
    top: -120,
    right: -40,
    width: 240,
    height: 240,
    borderRadius: 999,
    backgroundColor: palette.accentSoft,
  },
  backgroundShapeBottom: {
    position: 'absolute',
    bottom: 80,
    left: -80,
    width: 260,
    height: 260,
    borderRadius: 999,
    backgroundColor: '#dbe6dc',
  },
  hero: {
    paddingTop: 10,
    gap: 8,
  },
  heroEyebrow: {
    fontSize: 13,
    letterSpacing: 2.1,
    textTransform: 'uppercase',
    color: palette.accentDeep,
    fontFamily: Fonts.sans,
    fontWeight: '700',
  },
  heroTitle: {
    fontSize: 40,
    lineHeight: 48,
    color: palette.ink,
    fontFamily: Fonts.display,
    fontWeight: '700',
  },
  heroBody: {
    fontSize: 16,
    lineHeight: 24,
    color: palette.mutedInk,
    fontFamily: Fonts.sans,
  },
  card: {
    backgroundColor: palette.card,
    borderColor: palette.border,
    borderWidth: 1,
    borderRadius: 24,
    padding: 18,
    gap: 16,
    shadowColor: '#342b22',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 2,
  },
  cardHighlight: {
    borderColor: palette.accent,
    shadowOpacity: 0.12,
  },
  sectionHeader: {
    gap: 6,
  },
  sectionTitle: {
    fontSize: 24,
    lineHeight: 30,
    color: palette.ink,
    fontFamily: Fonts.display,
    fontWeight: '700',
  },
  sectionBody: {
    fontSize: 15,
    lineHeight: 22,
    color: palette.mutedInk,
    fontFamily: Fonts.sans,
  },
  segmentRow: {
    flexDirection: 'row',
    gap: 10,
  },
  segmentButton: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: '#f7f1e7',
  },
  segmentButtonSelected: {
    backgroundColor: palette.accent,
    borderColor: palette.accent,
  },
  segmentButtonText: {
    color: palette.ink,
    fontFamily: Fonts.sans,
    fontWeight: '700',
    fontSize: 16,
  },
  segmentButtonTextSelected: {
    color: '#fff7ee',
  },
  modeMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metaPill: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  metaPillAccent: {
    backgroundColor: palette.accentSoft,
  },
  metaPillSlate: {
    backgroundColor: palette.slateSoft,
  },
  metaPillGold: {
    backgroundColor: '#efe3c4',
  },
  metaPillGood: {
    backgroundColor: '#d6eadf',
  },
  metaPillEvil: {
    backgroundColor: '#f0d3d8',
  },
  metaPillText: {
    color: palette.ink,
    fontSize: 13,
    fontFamily: Fonts.sans,
    fontWeight: '600',
  },
  stack: {
    gap: 10,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  inputLabel: {
    width: 26,
    fontSize: 15,
    fontFamily: Fonts.sans,
    fontWeight: '700',
    color: palette.accentDeep,
    textAlign: 'center',
  },
  input: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: '#fffdf9',
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 16,
    fontFamily: Fonts.sans,
    color: palette.ink,
  },
  roleList: {
    gap: 8,
  },
  roleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#efe6d8',
  },
  roleName: {
    fontSize: 16,
    color: palette.ink,
    fontFamily: Fonts.sans,
    fontWeight: '600',
  },
  roleAlignment: {
    fontSize: 12,
    letterSpacing: 1.5,
    fontFamily: Fonts.sans,
    fontWeight: '700',
  },
  primaryButton: {
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: palette.accent,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  primaryButtonText: {
    color: '#fffaf5',
    fontSize: 16,
    fontFamily: Fonts.sans,
    fontWeight: '700',
  },
  disabledButton: {
    opacity: 0.45,
  },
  secondaryButton: {
    minHeight: 52,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    borderWidth: 1,
  },
  secondaryButtonEvil: {
    backgroundColor: '#f9e7ea',
    borderColor: '#d7a6b0',
  },
  secondaryButtonSlate: {
    backgroundColor: '#edf4f6',
    borderColor: '#bfd1d8',
  },
  secondaryButtonText: {
    fontSize: 16,
    fontFamily: Fonts.sans,
    fontWeight: '700',
  },
  selectableRow: {
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: '#fdf8f0',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 13,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  selectableRowSelected: {
    borderColor: palette.accent,
    backgroundColor: palette.accentSoft,
  },
  selectableTitle: {
    fontSize: 16,
    fontFamily: Fonts.sans,
    fontWeight: '700',
    color: palette.ink,
  },
  selectableSubtitle: {
    fontSize: 13,
    fontFamily: Fonts.sans,
    color: palette.mutedInk,
    marginTop: 3,
  },
  selectableMarker: {
    fontSize: 12,
    letterSpacing: 1.4,
    fontFamily: Fonts.sans,
    fontWeight: '700',
    color: palette.mutedInk,
  },
  selectableMarkerSelected: {
    color: palette.accentDeep,
  },
  boardGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  statBlock: {
    width: '48%',
    borderRadius: 18,
    padding: 14,
    gap: 6,
  },
  statBlockAccent: {
    backgroundColor: palette.accentSoft,
  },
  statBlockSlate: {
    backgroundColor: palette.slateSoft,
  },
  statBlockGold: {
    backgroundColor: '#efe3c4',
  },
  statBlockInk: {
    backgroundColor: '#e7e3dc',
  },
  statLabel: {
    fontSize: 12,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    color: palette.mutedInk,
    fontFamily: Fonts.sans,
  },
  statValue: {
    fontSize: 19,
    color: palette.ink,
    fontFamily: Fonts.display,
    fontWeight: '700',
  },
  historyRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  historyChip: {
    minWidth: 68,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  historyChipPending: {
    backgroundColor: '#eee7dc',
  },
  historyChipGood: {
    backgroundColor: '#d6eadf',
  },
  historyChipEvil: {
    backgroundColor: '#f0d3d8',
  },
  historyChipText: {
    color: palette.ink,
    fontSize: 13,
    fontFamily: Fonts.sans,
    fontWeight: '700',
    textAlign: 'center',
  },
  secretRoleBanner: {
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderWidth: 1,
    gap: 6,
  },
  secretRoleBannerGood: {
    backgroundColor: '#e2f1e8',
    borderColor: '#9ac2ad',
  },
  secretRoleBannerEvil: {
    backgroundColor: '#f6e1e5',
    borderColor: '#d4a0aa',
  },
  secretRoleLabel: {
    fontSize: 12,
    letterSpacing: 1.8,
    textTransform: 'uppercase',
    color: palette.mutedInk,
    fontFamily: Fonts.sans,
    fontWeight: '700',
  },
  secretRole: {
    fontSize: 34,
    lineHeight: 42,
    color: palette.ink,
    fontFamily: Fonts.display,
    fontWeight: '700',
  },
  secretTeam: {
    fontSize: 14,
    letterSpacing: 2,
    fontFamily: Fonts.sans,
    fontWeight: '700',
  },
  secretSummary: {
    fontSize: 16,
    lineHeight: 24,
    color: palette.ink,
    fontFamily: Fonts.sans,
  },
  secretIntel: {
    fontSize: 15,
    lineHeight: 22,
    color: palette.mutedInk,
    fontFamily: Fonts.sans,
  },
  goodText: {
    color: palette.good,
  },
  evilText: {
    color: palette.evil,
  },
  slateText: {
    color: palette.slate,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 10,
  },
  buttonColumn: {
    gap: 10,
  },
  voteRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#efe6d8',
  },
  voteName: {
    fontSize: 16,
    color: palette.ink,
    fontFamily: Fonts.sans,
    fontWeight: '600',
  },
  voteValue: {
    fontSize: 15,
    fontFamily: Fonts.sans,
    fontWeight: '700',
  },
  resultCenter: {
    alignItems: 'center',
    gap: 8,
  },
  resultHeadline: {
    fontSize: 30,
    lineHeight: 38,
    fontFamily: Fonts.display,
    color: palette.ink,
    fontWeight: '700',
  },
  resultMeta: {
    fontSize: 15,
    color: palette.mutedInk,
    fontFamily: Fonts.sans,
  },
  revealRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#efe6d8',
  },
  revealName: {
    flex: 1,
    fontSize: 16,
    fontFamily: Fonts.sans,
    fontWeight: '700',
    color: palette.ink,
  },
  revealRole: {
    flex: 1,
    fontSize: 15,
    fontFamily: Fonts.sans,
    color: palette.ink,
    textAlign: 'center',
  },
  revealTeam: {
    width: 64,
    fontSize: 12,
    textAlign: 'right',
    fontFamily: Fonts.sans,
    fontWeight: '700',
    letterSpacing: 1.3,
  },
  logRow: {
    borderRadius: 18,
    backgroundColor: '#faf4ea',
    padding: 14,
    gap: 6,
  },
  logHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logTitle: {
    fontSize: 16,
    color: palette.ink,
    fontFamily: Fonts.sans,
    fontWeight: '700',
  },
  logOutcome: {
    fontSize: 12,
    letterSpacing: 1.4,
    fontFamily: Fonts.sans,
    fontWeight: '700',
  },
  logBody: {
    fontSize: 14,
    lineHeight: 20,
    color: palette.mutedInk,
    fontFamily: Fonts.sans,
  },
});
